# Generated by Django 4.1.2 on 2022-11-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Datos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareas',
            name='completado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
